### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Arash1381-y** [Rayanesh-Sharif/Front-end#2]
TODO list

V 1.0.0
### Blog page
- [ ] infinite query
- [ ] picture size before loading

### writing blogs
- [ ] implement basic draft.js rich text editor
- [ ] implement picture and media and code block + (text editing)
- [ ] add autosave and farsi support
- [ ] save and store editor(react component)
